/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JPanels_Proyecto;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import proyectofinal_rapa.conexion_db;

/**
 *
 * @author josep
 */
public class reg_linea_inv extends javax.swing.JPanel {
    public conexion_db conexion = new conexion_db();
    /**
     * Creates new form reg_linea_inv
     */
    public reg_linea_inv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesPanelTglBtn = new javax.swing.ButtonGroup();
        PanelBtns = new javax.swing.JPanel();
        agregar_btn = new javax.swing.JToggleButton();
        editar_btn = new javax.swing.JToggleButton();
        eliminar_btn = new javax.swing.JToggleButton();
        principal_panel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        PanelBtns.setMaximumSize(new java.awt.Dimension(260, 31));

        opcionesPanelTglBtn.add(agregar_btn);
        agregar_btn.setText("AGREGAR");
        agregar_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0), 2));
        agregar_btn.setMargin(new java.awt.Insets(2, 30, 2, 90));
        agregar_btn.setPreferredSize(new java.awt.Dimension(80, 21));
        agregar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_btnActionPerformed(evt);
            }
        });
        PanelBtns.add(agregar_btn);

        opcionesPanelTglBtn.add(editar_btn);
        editar_btn.setText("EDITAR");
        editar_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        editar_btn.setPreferredSize(new java.awt.Dimension(80, 21));
        editar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_btnActionPerformed(evt);
            }
        });
        PanelBtns.add(editar_btn);

        opcionesPanelTglBtn.add(eliminar_btn);
        eliminar_btn.setText("ELIMINAR");
        eliminar_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 2));
        eliminar_btn.setPreferredSize(new java.awt.Dimension(80, 21));
        eliminar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_btnActionPerformed(evt);
            }
        });
        PanelBtns.add(eliminar_btn);

        add(PanelBtns);

        principal_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        principal_panel.setMinimumSize(new java.awt.Dimension(661, 441));
        principal_panel.setPreferredSize(new java.awt.Dimension(661, 441));
        principal_panel.setLayout(new java.awt.BorderLayout());
        add(principal_panel);
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    

    private void agregar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_btnActionPerformed
        // TODO add your handling code here:
        principal_panel.removeAll();
        reg_linea_inv_registrar rlir = new reg_linea_inv_registrar();
        rlir.setSize(416,205);
        principal_panel.add(rlir);
        principal_panel.revalidate();
        principal_panel.repaint();
    }//GEN-LAST:event_agregar_btnActionPerformed

    private void editar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_btnActionPerformed
        // TODO add your handling code here:
        principal_panel.removeAll();
        reg_linea_inv_editar rlie = new reg_linea_inv_editar();
        rlie.setSize(416,205);
        principal_panel.add(rlie);
        principal_panel.revalidate();
        principal_panel.repaint();
    }//GEN-LAST:event_editar_btnActionPerformed

    private void eliminar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_btnActionPerformed
        // TODO add your handling code here:
        principal_panel.removeAll();
        reg_linea_inv_eliminar rliel = new reg_linea_inv_eliminar();
        rliel.setSize(416,205);
        principal_panel.add(rliel);
        principal_panel.revalidate();
        principal_panel.repaint();
    }//GEN-LAST:event_eliminar_btnActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBtns;
    private javax.swing.JToggleButton agregar_btn;
    private javax.swing.JToggleButton editar_btn;
    private javax.swing.JToggleButton eliminar_btn;
    private javax.swing.ButtonGroup opcionesPanelTglBtn;
    private javax.swing.JPanel principal_panel;
    // End of variables declaration//GEN-END:variables
}
