/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JPanels_Proyecto;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josep
 */
public class reg_linea_inv extends javax.swing.JPanel {

    /**
     * Creates new form reg_linea_inv
     */
    public reg_linea_inv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesPanelTglBtn = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        agregar_btn = new javax.swing.JToggleButton();
        editar_btn = new javax.swing.JToggleButton();
        eliminar_btn = new javax.swing.JToggleButton();
        principal_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLineas = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        opcionesPanelTglBtn.add(agregar_btn);
        agregar_btn.setText("AGREGAR");
        agregar_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0), 2));
        agregar_btn.setMargin(new java.awt.Insets(2, 30, 2, 90));
        agregar_btn.setPreferredSize(new java.awt.Dimension(80, 21));
        agregar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_btnActionPerformed(evt);
            }
        });
        jPanel2.add(agregar_btn);

        opcionesPanelTglBtn.add(editar_btn);
        editar_btn.setText("EDITAR");
        editar_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        editar_btn.setPreferredSize(new java.awt.Dimension(80, 21));
        editar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_btnActionPerformed(evt);
            }
        });
        jPanel2.add(editar_btn);

        opcionesPanelTglBtn.add(eliminar_btn);
        eliminar_btn.setText("ELIMINAR");
        eliminar_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 2));
        eliminar_btn.setPreferredSize(new java.awt.Dimension(80, 21));
        eliminar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_btnActionPerformed(evt);
            }
        });
        jPanel2.add(eliminar_btn);

        jPanel1.add(jPanel2);

        principal_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        principal_panel.setPreferredSize(new java.awt.Dimension(200, 400));
        principal_panel.setLayout(new javax.swing.BoxLayout(principal_panel, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(principal_panel);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LINEAS DE INVESTIGACIÓN");
        jPanel1.add(jLabel1);

        tablaLineas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CLAVE", "NOMBRE DE LINEA", "FECHA AUTORIZACIÓN", "FECHA VIGENCIA"
            }
        ));
        tablaLineas.setPreferredSize(new java.awt.Dimension(100, 0));
        jScrollPane1.setViewportView(tablaLineas);

        jPanel1.add(jScrollPane1);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void agregar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_btnActionPerformed
        // TODO add your handling code here:
        principal_panel.removeAll();
        reg_linea_inv_registrar rlir = new reg_linea_inv_registrar();
        rlir.setSize(416,205);
        principal_panel.add(rlir);
        principal_panel.revalidate();
        principal_panel.repaint();
    }//GEN-LAST:event_agregar_btnActionPerformed

    private void editar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_btnActionPerformed
        // TODO add your handling code here:
        principal_panel.removeAll();
        reg_linea_inv_editar rlie = new reg_linea_inv_editar();
        rlie.setSize(416,205);
        principal_panel.add(rlie);
        principal_panel.revalidate();
        principal_panel.repaint();
    }//GEN-LAST:event_editar_btnActionPerformed

    private void eliminar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_btnActionPerformed
        // TODO add your handling code here:
        principal_panel.removeAll();
        reg_linea_inv_eliminar rliel = new reg_linea_inv_eliminar();
        rliel.setSize(416,205);
        principal_panel.add(rliel);
        principal_panel.revalidate();
        principal_panel.repaint();
    }//GEN-LAST:event_eliminar_btnActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton agregar_btn;
    private javax.swing.JToggleButton editar_btn;
    private javax.swing.JToggleButton eliminar_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup opcionesPanelTglBtn;
    private javax.swing.JPanel principal_panel;
    private javax.swing.JTable tablaLineas;
    // End of variables declaration//GEN-END:variables
}
