/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal_rapa;

import jPanels.docente_consulta;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author andresdam
 */
public class interfaz_docente extends javax.swing.JFrame implements ActionListener {

    docente_consulta dc = new docente_consulta();
    
    public interfaz_docente() {
        initComponents();
        this.setLocation(50, 100);
        etiNombre.setText("Jose Alfonso Perez Duran");
        
        btnAgregar.addActionListener(this);
        btnConsultar.addActionListener(this);
        
        dc.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        contenedor = new javax.swing.JPanel();
        pnlIzquierdo = new javax.swing.JPanel();
        etiBienvenido = new javax.swing.JLabel();
        etiNombre = new javax.swing.JLabel();
        pnlInferior = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JRadioButton();
        btnAgregar = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 546));

        contenedor.setLayout(new java.awt.BorderLayout());

        pnlIzquierdo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(255, 0, 0), null, null));
        pnlIzquierdo.setLayout(new java.awt.BorderLayout());

        etiBienvenido.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        etiBienvenido.setText("Bienvenido");
        pnlIzquierdo.add(etiBienvenido, java.awt.BorderLayout.PAGE_START);

        etiNombre.setText("nombreDocente");
        pnlIzquierdo.add(etiNombre, java.awt.BorderLayout.CENTER);

        pnlInferior.setLayout(new java.awt.BorderLayout());

        buttonGroup1.add(btnConsultar);
        btnConsultar.setText("Consultar participaciones");
        pnlInferior.add(btnConsultar, java.awt.BorderLayout.CENTER);

        buttonGroup1.add(btnAgregar);
        btnAgregar.setText("Agregar producto");
        pnlInferior.add(btnAgregar, java.awt.BorderLayout.PAGE_START);

        pnlIzquierdo.add(pnlInferior, java.awt.BorderLayout.PAGE_END);

        contenedor.add(pnlIzquierdo, java.awt.BorderLayout.LINE_START);

        getContentPane().add(contenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_docente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAgregar;
    private javax.swing.JRadioButton btnConsultar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel etiBienvenido;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JPanel pnlInferior;
    private javax.swing.JPanel pnlIzquierdo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        Object evt = ae.getSource();
        if(evt.equals(btnConsultar)){
            dc.setVisible(true);
            
            contenedor.add(dc); 
            contenedor.validate();
        } else{
            dc.setVisible(false);
        }
                
    }
}
